---
image: registry.salsa.debian.org/ganeti-team/ganeti-ci-images:debian-buster
stages:
  - build
  - install
  - test
build:
  stage: build
  artifacts:
    untracked: true
  script:
    - ./autogen.sh
    - ./configure --enable-haskell-tests
    - make
install:
  stage: install
  artifacts:
    untracked: true
  script:
    - make install
unittest:
  stage: test
  artifacts:
    untracked: true
  script:
    - make py-tests
    - make hs-tests
vcluster:
  stage: test
  artifacts:
    untracked: true
  script:
   - ./qa/vcluster-qa
   