---
image: registry.salsa.debian.org/ganeti-team/ganeti-ci-images:debian-buster
stages:
  - build
  - test
build:
  stage: build
  artifacts:
    untracked: true
  script:
    - ./autogen.sh
    - ./configure --enable-haskell-tests
    - make
    - make install
py-unittest:
  stage: test
  artifacts:
    untracked: true
  script:
    - make py-tests
hs-unittest:
  stage: test
  artifacts:
    untracked: true
  script:
    - make hs-tests
vcluster:
  stage: test
  artifacts:
    untracked: true
  script:
   - ./qa/vcluster-qa
   